### ISSUE TITLE
problem with using IO monad 

### ISSUE THREAD

**Issue by donnut** [monet/monet.js#14]
If made a copy of the IO example, but I am get the error object is not a function if I try the run it. It seems that `read` is an object instead of a function. I've made a gist to show the problem. Could you take a look to see what I'm doing wrong?

https://gist.github.com/donnut/a51c9fc1b8fba774f307

**Comment by cheshirecatalyst** [comment]
So following @puffnfresh advice, i now have the example working up until flatMap. At which point i recieve:

```
Users/emris/src/js/monads/node_modules/monet/src/main/javascript/monet.js:623
                return fn(self.effectFn()).run()
                       ^
TypeError: object is not a function
```

with this code

```javascript
require('monet')

function read() {
    return IO( function (){ return "A message" } )
}

function log(logFn) {
    return IO(function(value) {
        logFn(value)
    })
}

function toUpper(text) { return text.toUpperCase() }

var someIo = read().map(toUpper).flatMap(log(console.log))
someIo.run()
```

I have custom patched monet to actually modify the global node environment, so that it works as it does in the browser:

[monet.js:12](https://github.com/cwmyers/monet.js/blob/master/src/main/javascript/monet.js#L12)
turns into

```javascript
module.exports = factory(GLOBAL);
```
