### ISSUE TITLE
Io example (pt2)

### ISSUE THREAD

**Issue by dotmilk** [monet/monet.js#23]
So following @puffnfresh advice here #14 , i now have the example working up until flatMap. At which point i recieve:

```
Users/emris/src/js/monads/node_modules/monet/src/main/javascript/monet.js:623
                return fn(self.effectFn()).run()
                       ^
TypeError: object is not a function
```

with this code

``` javascript
require('monet')

function read() {
    return IO( function (){ return "A message" } )
}

function log(logFn) {
    return IO(function(value) {
        logFn(value)
    })
}

function toUpper(text) { return text.toUpperCase() }

var someIo = read().map(toUpper).flatMap(log(console.log))
someIo.run()
```

I have custom patched monet to actually modify the global node environment, so that it works as it does in the browser:

[monet.js:12](https://github.com/cwmyers/monet.js/blob/master/src/main/javascript/monet.js#L12)
turns into

``` javascript
module.exports = factory(GLOBAL);
```

**Comment by cwmyers** [comment]
Thanks for following this up.  Much appreciated.

**Comment by WojciechP** [comment]
Hello,
AFAIK the only way to create a valid `IO` instance is by calling `IO(() => {...}`. In the function `log` you're returning `IO(function(value) { logFn(value) })`, but the IO expects a function with no arguments. As a result, `value` will be `undefined`, which is not what you want. I haven't checked that, but I think you will need to refactor to something like this:

```
function log(logFn) {
  return function(message) {
    return IO(function() { logFn(message) }
  }
}
```

Also, doing `log(console.log)` might yield surprising results, because it "unbinds" the `log` method from the `console` object. For example in Chrome saying `var f = console.log; f(2)` throws an error. A possible workaround may look like this:

```
var logToConsole = log(console.log.bind(console))
var someIo = read().map(toUpper).flatMap(logToConsole)
```
I hope this helps. Also, @ulfryk has written a series a posts on monads in monet - they might provide more information. Feel free to read them at https://tech.evojam.com/author/kuba/.

**Comment by char0n** [comment]
I guess this may be related to https://github.com/monet/monet.js/issues/110.  The docs concerning the IO monad had already been fixed here: https://monet.github.io/monet.js/#io
