### ISSUE TITLE
Possibility to shorten these type parameters declarations?

### ISSUE THREAD

**Issue by mostr** [monet/monet.js#87]
When using e.g. `Either` from with typescript it's always required to put both type parameters when creating instance e.g.

 ``` typescript
   function activateUser(user: User): Either<Err, User> {
      // ... do stuff here
      if(cannotBeActivated(user)) {
        return Left<Err, User>(Err.of('Cannot be activated');
      }
      return Right<Err, User>(user)
    }
```

Notice this kind of redundant type parameters in both `return` statements (`Left<Err, User>` and `Right<Err, User>`). 

I wonder if there is a way to provide some kind of type alias, like 

**does-not-compile code ahead**:

1.

``` typescript
    import {Either, Right, Left} from "monet";
    type Result = Either<Err, User>
    // ...
    return Result.Right(user)
```
gives `TS2693: 'Result' only refers to a type but is being used as a value here`

2.

``` typescript
    import {Either, Right, Left} from "monet";
    type Ok = Right<Err, User>
    type NotOk = Left<Err, User>
    // ...
    return Ok(user)
```
gives `TS2304: Cannot find name Right`

I see why these can be wrong, so my question is whether it's possible (and if so, how?) to achieve similar result that compiles and makes these definitions shorter? I guess it's more of a question to @ulfryk as he's the one delivering TS goodies to monet :)

**Comment by ulfryk** [comment]
@mostr This issue is also bothering me :|

First a tip - you don't need to specify return type of `activateUser` function, as TS will infer it correctly from return statements.

For some `hack` that may help you can try sth like:

```typescript
import { Either, Left, Right } from 'monet'

const Ok: (val: User) => Either<Error, User> = Right
const NotOk: (err: Error) => Either<Error, User> = Left

// ...

return Ok(user)
```

I'm also thinking about upgrading these typings so one have only to define one type when using `Left` or `Right` constructor, but I'm not 100% sure now that it's possible - TS has its limitations…

**Comment by mostr** [comment]
Good to know I'm not the only one that would love to make this better :) Regarding function type, I know - I just prefer to have it in place for my "public" API, just to be sure I return "correct" type of value (especially when async&promises are in play and TS can easily generalize it to `Promise<any>` or `Promise<some|union|type>` which is not what I usually want). 

I was about to try something similar to your hack - should go as a workaround for now, thanks!

If talking about `Either`... do you folks have any plans shipping something similar to monad-transformers that would allow mixing Promises with Eithers, Maybes etc any time soon? Right now I use my home-grown `EitherP` and `MaybeP` (specialized, due to lack of HKT in TS) but would be great to see something more generic if possible.

**Comment by ulfryk** [comment]
Now we're focused on cleaning, extending and documenting what is already done. I know that @cwmyers made an attempt on transformers but he decided not to make them public for now. TS is somehow limited…

See:
- https://github.com/cwmyers/monet.js/issues/39
- https://github.com/cwmyers/monet.js/issues/5

But I think no work has been done since then.

**Comment by mostr** [comment]
Sure, got it. Thanks for the heads-up on that & feel free to close this issue now.
